### ISSUE TITLE
Initial set up

### ISSUE THREAD

**Issue by sbojorge** [sbojorge/Urban-drf#2]
EPIC #1 
As a **developer** I can **initiate my django project** so that **it can be ready for development and run locally**.

## Acceptance criteria
  * Acceptance criteria 1: A supported Django version is installed as well as the libraries required for the first deployment.
  * Acceptance criteria 2:  There is a requirements.txt file for keeping track of all the installed dependencies all along the development process.
  * Acceptance criteria 3: There is a project and an application.

 ## Tasks
 - [x] Task 1:  Install Django and the supporting libraries (gunicorn, psycopg2, dj_database_url).
 - [x] Taks 2: Create the requirements.txt file and record the currently  installed dependencies in it.
 - [x] Task 3: Create the drf-urban project and the profiles app.
 - [x] Task 4: Add the app to the INSTALLED_ APPS in settings.py and run the required migrations.

**Comment by chukaibejih** [comment]
Hi Sara,

I came across your repository while randomly going through DRF projects, and I must say that I love how you have organized your projects and broken them into tasks, EPICs, user stories, and other methodologies you used. This is something I would love to adopt in my future projects.

I especially appreciate the way you have clearly defined the scope of each task and the way you have linked the tasks together into a logical progression. This makes it very easy to understand what needs to be done, and how each task fits into the overall project.

I also like the way you have included user stories in your project. This helps to ensure that the project is focused on the needs of the users and that the features that are developed are actually valuable to them.

Overall, I think your project is a great example of how to organize and structure a DRF project. I would be very grateful if you could share any tips or resources that you used.

Cheers,
Ibejih
